### ISSUE TITLE
Forgot Password Link Not Working

### ISSUE THREAD

**Issue by ramosamuel** [muhazrisofyan/Tjetak-Desainer#6]
Link yang dikirimkan melalui email setelah melakukan forgot password tidak berfungsi dan memunculkan page berikut.

<img width="1279" alt="screen shot 2018-02-13 at 14 00 08" src="https://user-images.githubusercontent.com/17270473/36137285-0fe0635e-10c7-11e8-801e-c1c63528921b.png">

**Comment by muhazrisofyan** [comment]
Hal tersebur dikarenakan file .env yang digunakan atribut APP_URL yg digunakan adalah http://localhost sedangkan development server yang digunakan laravel adalah http://localhost:8000, dan kemarin yang di push di .env.development belum diubah jadi localhost:8000
